<link rel="icon" href="/img/favicon.png">
<script src="/js/jquery-3.1.1.min.js" type="text/javascript"></script>
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Bootstrap -->
<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/bootstrap/js/bootstrap.min.js"></script>

<script>
    jQuery.ajax({
        type: "GET",
        url: 'http://apiphp.local/api/users',
        success: function (data) {
            var html =
                '<table class="table table-striped">'+
                '<thead>'+
                '<tr>'+
                '<th>#</th>'+
                '<th>Name</th>'+
                '<th>Email</th>'+
                '<th>Ações</th>'+
                '<tr>'+
                '</thead>';

            var data = data.data;
            var count = 1;
            data.forEach(function (entry) {
                html += '<tbody>'+
                    '<tr>'+
                    '<th scope="row">'+(count++)+'</th>'+
                    '<td>'+entry.name+'</td>'+
                    '<td>'+entry.email+'</td>'+
                    '<td>'+
                        '<button type="button" class="btn btn-warning" value='+entry.id+'>Alterar</button> '+
                        '<button type="button" class="btn btn-danger"  onclick="deleteUser('+entry.id+')">Deletar</button>'+
                    '</td>'+
                    '</tr>'+
                    '</tbody>';
            });

            html += '</table>';
            $('#info').html(html);
        }
    });

function deleteUser(userId) {
    if(userId != null){
     var result =   confirm("Você deseja pagar o usuario" +userId);
         if(result == true){
             jQuery.ajax({
                 type: "DELETE",
                 url: "http://apiphp.local/api/users/"+userId,
                 success: function (data) {
                     location.reload();
                 },
                 error: function (data){
                     console.log(data);
                 }
             });
         }
     }
}
</script>

<html>
<head>
    <title>Lista de usuários</title>
</head>
<body>

<div id="info">

</div>

</body>
</html>
