Route: / Controller: BlaController Action:bla View: bla
<script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>

<script>
    $.ajax({
        type: "GET",
        url: 'http://api-php-site/api/robots/4',
        success: function(data) {
            $('info').html(data);
        },
        beforeSend: function(){
            $('.loader').css({display:"block"});
        },
        complete: function(){
            $('.loader').css({display:"none"});
        }
    });
</script>

<html>
<head>
    <title>Consultando api</title>
</head>
<body>
<div id="info"></div>

</body>
</html>
